/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/646d9dcdc8a5f5bddbfac913.glb -o src/components/Avatar.jsx -r public
*/
import { useAnimations, useFBX, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useControls, levaStore as store } from "leva";
import React, { useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

export function Avatar(props) {
  const [reloadKey, setReloadKey] = useState(0);
  const {
    playAudio,
    script,
    headFollow,
    smoothMorphTarget,
    morphTargetSmoothing,
    isGenerating,
    lipsyncGain = 1.2,  // Tu peux ajuster cette valeur fixe ici (1.2 ou 1 selon tes tests)
  } = useControls({
    playAudio: false,  // Toujours false par défaut → pas de lecture automatique
    headFollow: true,
    smoothMorphTarget: true,
    morphTargetSmoothing: 0.5,
    script: {
      value: "aro",
      options: ["welcome", "pizzas", "aro"],
    },
    isGenerating: false,
    lipsyncGain: { value: 1.2, min: 1, max: 10, step: 0.1 },
  });

  const audio = useMemo(() => {
    const a = new Audio(`/audios/${script}.mp3?v=${reloadKey}`);
    a.volume = 1;
    a.muted = false;
    return a;
  }, [script, reloadKey]);

  // Refs pour Web Audio API
  const audioContextRef = useRef(null);
  const analyserRef = useRef(null);
  const sourceRef = useRef(null);
  const dataArrayRef = useRef(null);

  // Configuration AudioContext + Analyser (son activé)
  useEffect(() => {
    const context = new (window.AudioContext || window.webkitAudioContext)();
    const analyser = context.createAnalyser();
    analyser.fftSize = 512;
    const bufferLength = analyser.frequencyBinCount;
    dataArrayRef.current = new Uint8Array(bufferLength);

    audioContextRef.current = context;
    analyserRef.current = analyser;

    if (audio.src) {
      const source = context.createMediaElementSource(audio);
      source.connect(analyser);
      analyser.connect(context.destination);  // Son sort des haut-parleurs
      sourceRef.current = source;
    }

    return () => {
      if (sourceRef.current) {
        sourceRef.current.disconnect();
        analyser.disconnect();
      }
    };
  }, [audio]);

  const group = useRef();
  const { nodes, materials } = useGLTF("/models/aro.glb");

  // Animations FBX
  const { animations: idleAnimation } = useFBX("/animations/Idle.fbx");
  const { animations: angryAnimation } = useFBX("/animations/Angry Gesture.fbx");
  const { animations: greetingAnimation } = useFBX("/animations/Standing Greeting.fbx");
  const { animations: thinkingAnimation } = useFBX("/animations/Speak.fbx");
  const { animations: talkingAnimation } = useFBX("/animations/Talking.fbx");
  const { animations: reflAnimation } = useFBX("/animations/Refl.fbx");

  idleAnimation[0].name = "Idle";
  angryAnimation[0].name = "Angry";
  greetingAnimation[0].name = "Greeting";
  thinkingAnimation[0].name = "Think";
  talkingAnimation[0].name = "Talk";
  reflAnimation[0].name = "Refl";

  const [animation, setAnimation] = useState("Idle");
  const { actions, mixer } = useAnimations(
    [idleAnimation[0], angryAnimation[0], greetingAnimation[0], thinkingAnimation[0], talkingAnimation[0], reflAnimation[0]],
    group
  );

  // === SUPPRIMÉ COMPLÈTEMENT : l'effect canplaythrough qui déclenchait la lecture automatique ===
  // Cela évite tout lancement d'audio au refresh de la page, même si aro.mp3 existe déjà.

  // Lecture / pause + choix animation (dépend uniquement de playAudio contrôlé par la génération)
  useEffect(() => {
    if (playAudio) {
      audio.currentTime = 0;
      audio.play().catch(err => console.error("Play bloqué :", err));

      if (script === "aro") {
        const anims = ["Think", "Talk"];
        const randomAnim = anims[Math.floor(Math.random() * anims.length)];
        setAnimation(randomAnim);
      } else {
        setAnimation("Idle");
      }
    } else {
      audio.pause();
      setAnimation("Idle");
    }
  }, [playAudio, audio, script]);

  // Lipsync en temps réel (analyse fréquentielle)
  useFrame(() => {
    const analyser = analyserRef.current;
    const head = nodes.Wolf3D_Head;
    const teeth = nodes.Wolf3D_Teeth;

    if (!analyser || !head || !teeth) return;

    const dict = head.morphTargetDictionary;
    const dataArray = dataArrayRef.current;

    const visemeNames = [
      "viseme_PP", "viseme_kk", "viseme_I", "viseme_AA",
      "viseme_O", "viseme_U", "viseme_FF", "viseme_TH"
    ];

    // Reset/lissage vers 0
    visemeNames.forEach((name) => {
      const idx = dict[name];
      if (idx !== undefined) {
        head.morphTargetInfluences[idx] = THREE.MathUtils.lerp(head.morphTargetInfluences[idx], 0, morphTargetSmoothing);
        teeth.morphTargetInfluences[idx] = THREE.MathUtils.lerp(teeth.morphTargetInfluences[idx], 0, morphTargetSmoothing);
      }
    });

    if (audio.paused || audio.ended) return;

    analyser.getByteFrequencyData(dataArray);

    const numBins = dataArray.length;
    const lowEnd = Math.floor(numBins * 0.15);
    const midEnd = Math.floor(numBins * 0.55);

    let lowAvg = 0;
    for (let i = 0; i < lowEnd; i++) lowAvg += dataArray[i];
    lowAvg = (lowAvg / lowEnd / 255) * lipsyncGain;

    let midAvg = 0;
    for (let i = lowEnd; i < midEnd; i++) midAvg += dataArray[i];
    midAvg = (midAvg / (midEnd - lowEnd) / 255) * lipsyncGain;

    let highAvg = 0;
    for (let i = midEnd; i < numBins; i++) highAvg += dataArray[i];
    highAvg = (highAvg / (numBins - midEnd) / 255) * lipsyncGain;

    const targets = {
      viseme_O: Math.min(1, lowAvg),
      viseme_U: Math.min(1, lowAvg * 0.8),
      viseme_AA: Math.min(1, midAvg),
      viseme_I: Math.min(1, highAvg),
      viseme_FF: Math.min(1, highAvg * 0.6),
      viseme_TH: Math.min(1, highAvg * 0.4),
      viseme_PP: Math.min(1, midAvg * 0.5),
      viseme_kk: Math.min(1, lowAvg * 0.5),
    };

    visemeNames.forEach((name) => {
      const target = targets[name] || 0;
      const idx = dict[name];
      if (idx !== undefined) {
        if (smoothMorphTarget) {
          head.morphTargetInfluences[idx] = THREE.MathUtils.lerp(head.morphTargetInfluences[idx], target, morphTargetSmoothing);
          teeth.morphTargetInfluences[idx] = THREE.MathUtils.lerp(teeth.morphTargetInfluences[idx], target, morphTargetSmoothing);
        } else {
          head.morphTargetInfluences[idx] = target;
          teeth.morphTargetInfluences[idx] = target;
        }
      }
    });
  });

  // Head follow camera
  useFrame((state) => {
    if (headFollow) {
      group.current.getObjectByName("Head").lookAt(state.camera.position);
    }
  });

  // Animation pendant génération
  useEffect(() => {
    if (isGenerating) {
      audio.pause();
      if (animation !== "Refl") {
        setAnimation("Refl");
      } else {
        const action = actions["Refl"];
        if (action) action.reset().fadeIn(0.5).play();
      }
    }
  }, [isGenerating, animation, actions, audio]);

  // Gestion animations
  useEffect(() => {
    const currentAction = actions[animation];
    if (currentAction) {
      currentAction.reset().fadeIn(0.5).play();
      if (animation === "Think" || animation === "Talk" || (animation === "Greeting" && !isGenerating)) {
        currentAction.loop = THREE.LoopOnce;
        currentAction.clampWhenFinished = true;
      } else {
        currentAction.loop = THREE.LoopRepeat;
      }
    }

    const onFinished = (e) => {
      if (e.action === currentAction && script === "aro" && !audio.paused && !audio.ended) {
        const anims = ["Think", "Talk"];
        const randomAnim = anims[Math.floor(Math.random() * anims.length)];
        setAnimation(randomAnim);
      }
    };
    mixer.addEventListener("finished", onFinished);

    return () => {
      if (currentAction) currentAction.fadeOut(0.5);
      mixer.removeEventListener("finished", onFinished);
    };
  }, [animation, actions, mixer, script, audio, isGenerating]);

  // Fin audio → stop playAudio
  useEffect(() => {
    const onAudioEnd = () => store.set({ playAudio: false });
    audio.addEventListener("ended", onAudioEnd);
    return () => audio.removeEventListener("ended", onAudioEnd);
  }, [audio]);

  // Événement génération audio → recharge + démarre la lecture UNIQUEMENT après génération
  useEffect(() => {
    const handleAudioGenerated = () => {
      store.set({ script: "aro" });
      setReloadKey((k) => k + 1);
      store.set({ playAudio: true });  // ← Lecture déclenchée seulement ici
    };
    window.addEventListener("audioGenerated", handleAudioGenerated);
    return () => window.removeEventListener("audioGenerated", handleAudioGenerated);
  }, []);

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom001.geometry} material={materials['Wolf3D_Outfit_Bottom.001']} skeleton={nodes.Wolf3D_Outfit_Bottom001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear001.geometry} material={materials['Wolf3D_Outfit_Footwear.001']} skeleton={nodes.Wolf3D_Outfit_Footwear001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top001.geometry} material={materials['Wolf3D_Outfit_Top.001']} skeleton={nodes.Wolf3D_Outfit_Top001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair001.geometry} material={materials['Wolf3D_Hair.001']} skeleton={nodes.Wolf3D_Hair001.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Wolf3D_Glasses.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  );
}

useGLTF.preload("/models/aro.glb");